---
include:
  - board: eyelash_corne_left
    shield: nice_view
    artifact-name: scorpio3-left
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: scorpio3-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: scorpio3-settings_reset
